import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    // "",
    {
      text: "DayZ模组",
      icon: "folder-open",
      prefix: "dayzmoddocs/",
      link: "dayzmoddocs/",
      collapsible: true,
      expanded: false,
      children: [
        {
          text: "服务端模组",
          icon: "folder-open",
          prefix: "servermod/",
          link: "servermod/",
          collapsible: true,
          expanded: false,
          children: [
            {   //食物类
              text: "食物类",
              icon: "folder-open",
              prefix: "foods/",
              link: "foods/",
              collapsible: true,
              expanded: false,
              children: "structure",
            },
            {   //医疗类
              text: "医疗类",
              icon: "folder-open",
              prefix: "medical/",
              link: "medical/",
              collapsible: true,
              expanded: false,
              children: "structure",
            },
            {   //规则类
              text: "规则类",
              icon: "folder-open",
              prefix: "game_rules/",
              link: "game_rules/",
              collapsible: true,
              expanded: false,
              children: "structure",
            },
            {   //载具类
              text: "载具类",
              icon: "folder-open",
              prefix: "vehicles/",
              link: "vehicles/",
              collapsible: true,
              expanded: false,
              children: "structure",
            },
          ],
        },
        {
          text: "客户端模组",
          icon: "folder-open",
          prefix: "clientmod/",
          link: "clientmod/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
      ],
    },
    {
      text: "官方API",
      icon: "folder-open",
      prefix: "scriptsapi/",
      link: "scriptsapi/",
      children: [
        {
          text: "1_core",
          icon: "folder-open",
          prefix: "1_core/",
          link: "1_core/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "2_gamelib",
          icon: "folder-open",
          prefix: "2_gamelib/",
          link: "2_gamelib/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "3_game",
          icon: "folder-open",
          prefix: "3_game/",
          link: "3_game/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "4_world",
          icon: "folder-open",
          prefix: "4_world/",
          link: "4_world/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "5_mission",
          icon: "folder-open",
          prefix: "5_mission/",
          link: "5_mission/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
      ],
    },
  ],
});
